### ISSUE TITLE
no syslog option

### ISSUE THREAD

**Issue by derekn** [pyther/goeap_proxy#3]
the documentation says there is a "-syslog" option for writing logs to syslog instead of stdout, there doesnt appear to be this option.

**Comment by pyther** [comment]
Thanks for reporting this. I removed the option a while back when refactoring the code. Is this a feature that you need?

With openwrt, if you use an init script the output will go to the log. With systemd the output will go to the journal. For other platforms/systems you could pipe the output to logger.

**Comment by derekn** [comment]
ah ok. I use it on Asus Merlin firmware which doesn't use an init script, but I might try piping it to logger

**Comment by pyther** [comment]
README.md has been updated.
